Attribute VB_Name = "DeclareVariables"
Public m_nDevIndex As Long
Public m_nCalData(31) As Integer
Public m_nCH1VoltDIV As Long
Public m_nCH2VoltDIV As Long
Public m_nTimeDIV As Long
Public m_nCH1Data(10239) As Integer
Public m_nCH2Data(10239) As Integer
Public dataInput As String
Public comaSeparator As String
Public xCoordinate As Integer
Public yCoordinate As Integer
Public xCoordinates As String
Public yCoordinates As String
Public x As Integer
Public y As Integer
Public mili2Pixel As Integer
Public border As Integer
Public dataOutput As String
Public dataOutput1 As String
Public vmaxDataCH1 As Integer
Public vmaxDataCH2 As Integer
Public vminDataCH1 As Integer
Public vminDataCH2 As Integer
Public vppdataCH1 As Double
Public vrmsDataCH1 As Double
Public vppdataCH2 As Double
Public vrmsDataCH2 As Double
Public gain As Double
Public damageLevel As Double
Public damageLevelRange100 As Integer
Public minDamageLevel As Double
Public maxDamageLevel As Double
Public strLine As String
Public fso As New FileSystemObject
Public fsoStream As TextStream
Public coordinateSaveData(500, 500) As String
